import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar/Navbar";
import Footer from "@/components/footer/footer";
import Provider from "@/context/Provider";
import Toster from "@/context/Toster";
// Import Font Awesome CSS in your component or layout
import "@fortawesome/fontawesome-svg-core/styles.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DSCE ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <NavBar />
          {children}
          <Footer />
          <Toster />
        </body>
      </Provider>
    </html>
  );
}
