import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "@/components/Navbar/Navbar";
import Provider from "@/context/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DSCE ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={inter.className}>
          <NavBar>{children}</NavBar>
        </body>
      </Provider>
    </html>
  );
}
