// NextRequest {
//     [Symbol(realm)]: { settingsObject: { baseUrl: undefined } },
//     [Symbol(state)]: {
//       method: 'GET',
//       localURLsOnly: false,
//       unsafeRequest: false,
//       body: null,
//       client: { baseUrl: undefined },
//       reservedClient: null,
//       replacesClientId: '',
//       window: 'client',
//       keepalive: false,
//       serviceWorkers: 'all',
//       initiator: '',
//       destination: '',
//       priority: null,
//       origin: 'client',
//       policyContainer: 'client',
//       referrer: 'client',
//       referrerPolicy: '',
//       mode: 'cors',
//       useCORSPreflightFlag: false,
//       credentials: 'same-origin',
//       useCredentials: false,
//       cache: 'default',
//       redirect: 'follow',
//       integrity: '',
//       cryptoGraphicsNonceMetadata: '',
//       parserMetadata: '',
//       reloadNavigation: false,
//       historyNavigation: false,
//       userActivation: false,
//       taintedOrigin: false,
//       redirectCount: 0,
//       responseTainting: 'basic',
//       preventNoCacheCacheControlHeaderModification: false,
//       done: false,
//       timingAllowFailed: false,
//       headersList: HeadersList {
//         [Symbol(headers map)]: [Map],
//         [Symbol(headers map sorted)]: [Map]
//       },
//       urlList: [ [URL] ],
    //    url: URL {
    //      href: 'http://[::1]:3000/api/problem/65022f44785fe53735f9a99d',
    //      origin: 'http://[::1]:3000',
    //      protocol: 'http:',
    //      username: '',
    //      password: '',
    //      host: '[::1]:3000',
    //      hostname: '[::1]',
    //      port: '3000',
    //      pathname: '/api/problem/65022f44785fe53735f9a99d',
    //      search: '',
    //      searchParams: URLSearchParams {},
    //      hash: ''
    //    }
    //  },
    //  [Symbol(signal)]: AbortSignal { aborted: false },
//     [Symbol(headers)]: HeadersList {
//       [Symbol(headers map)]: Map(20) {
//         'accept' => '*/*',
//         'accept-encoding' => 'gzip, deflate',
//         'accept-language' => 'en-US,en',
//         'cache-control' => 'max-age=0',
//         'connection' => 'keep-alive',
//         'cookie' => 'next-auth.csrf-token=8bdd51e1ada23684867dba87ae0d230be3ada9231ebf5030c0a07021205e0847%7C338e73302b666da7890a675c738c1711390617ef932e4e47b54744bbeaafaadb; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsignin; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..YmLSUgaBnaX_twWQ.j_R0CgacZkLCo4ljmT22G-rieE-kP8BuRfdAxdlmvrhtM5ETHcoG6ENu4Ju4Vha77vQw_sbz6DwG85qMDanD-Bc04zpXKbpi9P-El7I-FSmKeWT8S8vlBbjwKODYgtpRUmMzNb6YmvnwjzJ1j6L2cTJLkulay9zhUKAyS75YCvAa7KhttYLeZO8PFc_EFoj3XjZ-8goRqnBrqTlquw53FViYTjVYSA5uJTbpg1JPfKUVwmuxmuzcX7XMC85u.DKxXPMWA8d8ELHYShfukdg',
//         'host' => 'localhost:3000',
//         'referer' => 'http://localhost:3000/allProblems/65022f44785fe53735f9a99d',
//         'sec-ch-ua' => '"Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"',
//         'sec-ch-ua-mobile' => '?0',
//         'sec-ch-ua-platform' => '"Windows"',
//         'sec-fetch-dest' => 'empty',
//         'sec-fetch-mode' => 'cors',
//         'sec-fetch-site' => 'same-origin',
//         'sec-gpc' => '1',
//         'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
//         'x-invoke-output' => '/api/problem/[id]',
//         'x-invoke-path' => '/api/problem/65022f44785fe53735f9a99d',
//         'x-invoke-query' => '%7B%7D',
//         'x-middleware-invoke' => ''
//       },
//       [Symbol(headers map sorted)]: Map(20) {
//         'accept' => '*/*',
//         'accept-encoding' => 'gzip, deflate',
//         'accept-language' => 'en-US,en',
//         'cache-control' => 'max-age=0',
//         'connection' => 'keep-alive',
//         'cookie' => 'next-auth.csrf-token=8bdd51e1ada23684867dba87ae0d230be3ada9231ebf5030c0a07021205e0847%7C338e73302b666da7890a675c738c1711390617ef932e4e47b54744bbeaafaadb; next-auth.callback-url=http%3A%2F%2Flocalhost%3A3000%2Fsignin; next-auth.session-token=eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..YmLSUgaBnaX_twWQ.j_R0CgacZkLCo4ljmT22G-rieE-kP8BuRfdAxdlmvrhtM5ETHcoG6ENu4Ju4Vha77vQw_sbz6DwG85qMDanD-Bc04zpXKbpi9P-El7I-FSmKeWT8S8vlBbjwKODYgtpRUmMzNb6YmvnwjzJ1j6L2cTJLkulay9zhUKAyS75YCvAa7KhttYLeZO8PFc_EFoj3XjZ-8goRqnBrqTlquw53FViYTjVYSA5uJTbpg1JPfKUVwmuxmuzcX7XMC85u.DKxXPMWA8d8ELHYShfukdg',
//         'host' => 'localhost:3000',
//         'referer' => 'http://localhost:3000/allProblems/65022f44785fe53735f9a99d',
//         'sec-ch-ua' => '"Brave";v="117", "Not;A=Brand";v="8", "Chromium";v="117"',
//         'sec-ch-ua-mobile' => '?0',
//         'sec-ch-ua-platform' => '"Windows"',
//         'sec-fetch-dest' => 'empty',
//         'sec-fetch-mode' => 'cors',
//         'sec-fetch-site' => 'same-origin',
//         'sec-gpc' => '1',
//         'user-agent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36',
//         'x-invoke-output' => '/api/problem/[id]',
//         'x-invoke-path' => '/api/problem/65022f44785fe53735f9a99d',
//         'x-invoke-query' => '%7B%7D',
//         'x-middleware-invoke' => ''
//       }
//     },
//     [Symbol(internal request)]: {
//       cookies: RequestCookies { _parsed: [Map], _headers: [HeadersList] },
//       geo: {},
//       ip: undefined,
//       nextUrl: NextURL { [Symbol(NextURLInternal)]: [Object] },
//       url: 'http://localhost:3000/api/problem/65022f44785fe53735f9a99d'
//     }
//   }